[package]
name = "ping_test"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = { version = "3.4.7", features = ["termination"] }


[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"
